-- RemoSpot — seed the spots table (Phase 2 STEP 1)
-- Generated from src/data/spots.ts. Paste into the Supabase SQL editor and Run.
-- id is omitted so Postgres generates UUIDs; space_family/score_label are
-- forced to remote-work defaults; wifi/noise/sockets live in type_attributes.
-- Safe to run once on an empty table (the app query orders by work_score desc).

insert into public.spots
  (name, neighbourhood, type, space_family, score_label, description,
   cover_gradient, type_attributes, vibe_tags, best_times, work_score,
   review_count, price_entry, price_type)
values
  ('The Alchemist', 'Westlands', 'garden', 'remote_work', 'WorkScore', 'A sprawling open-air garden in the heart of Westlands with multiple bar and food vendors. Mornings are calm and surprisingly productive — great WiFi, plenty of shade, and a creative crowd. Gets loud after 2pm on weekends. The back courtyard has the best socket access.', 'linear-gradient(135deg, #2E4A3A 0%, #1C3028 100%)', '{"wifi_mbps":78,"noise_level":1,"sockets":"Abundant"}'::jsonb, ARRAY['🌿 Outdoor', '🎨 Creative Crowd', '☕ Good Coffee']::text[], ARRAY['7am–11am ✓', '11am–1pm', '1pm–3pm', '3pm–6pm ✓', 'After 6pm ✗']::text[], 9.2, 0, 'Min. KES 400', 'free'),
  ('Nairobi Garage', 'Kilimani', 'cowork', 'remote_work', 'WorkScore', 'Nairobi''s original tech-focused coworking space, now with multiple floors and event spaces. The community is its biggest asset — engineers, founders, and consultants all share the floor. A day pass buys you unlimited coffee, a dedicated desk, and access to call booths.', 'linear-gradient(135deg, #3D2B1F 0%, #6B4226 100%)', '{"wifi_mbps":120,"noise_level":2,"sockets":"Excellent"}'::jsonb, ARRAY['💻 Tech Community', '📞 Call Booths', '☕ Free Coffee']::text[], ARRAY['8am–12pm ✓', '12pm–2pm', '2pm–5pm ✓', 'After 5pm']::text[], 8.8, 0, 'KES 1,500/day', 'paid'),
  ('Karen Blixen Coffee Garden', 'Karen', 'garden', 'remote_work', 'WorkScore', 'A truly beautiful setting — colonial-era gardens, giant fig trees, and birdsong. The WiFi is solid for its class and the clientele skews toward consultants and visiting professionals. Ideal for creative work, calls, or meetings you want to impress at.', 'linear-gradient(135deg, #1A3320 0%, #2E5235 100%)', '{"wifi_mbps":55,"noise_level":1,"sockets":"Moderate"}'::jsonb, ARRAY['🌳 Stunning Grounds', '🤝 Client Meetings', '🤫 Very Quiet']::text[], ARRAY['8am–11am ✓', '11am–1pm ✓', '1pm–3pm', '3pm–5pm ✓']::text[], 8.9, 0, 'Min. KES 600', 'free'),
  ('The Social House', 'Gigiri', 'cafe', 'remote_work', 'WorkScore', 'Stylish café in the Gigiri diplomatic zone popular with NGO workers and UN staff. Excellent flat whites, solid WiFi, and a calm buzzy energy. The terrace is the best spot for video calls.', 'linear-gradient(135deg, #2A3545 0%, #3D5070 100%)', '{"wifi_mbps":65,"noise_level":2,"sockets":"Good"}'::jsonb, ARRAY['🌍 International Crowd', '📹 Good for Calls', '☕ Specialty Coffee']::text[], ARRAY['8am–10am ✓', '10am–12pm ✓', '12pm–2pm', '2pm–5pm ✓']::text[], 8.1, 0, 'Min. KES 500', 'free'),
  ('iHub Nairobi', 'Upperhill', 'cowork', 'remote_work', 'WorkScore', 'Africa''s original tech hub, reimagined. iHub is more than a coworking space — it''s a community of builders, developers, and innovators. The day pass includes access to the events calendar and meeting rooms.', 'linear-gradient(135deg, #2A1A35 0%, #4A2A60 100%)', '{"wifi_mbps":95,"noise_level":2,"sockets":"Excellent"}'::jsonb, ARRAY['🚀 Startup Energy', '💻 Tech Focused', '📚 Resource Library']::text[], ARRAY['8am–12pm ✓', '2pm–6pm ✓']::text[], 8.5, 0, 'KES 1,200/day', 'paid'),
  ('Java House — Westlands', 'Westlands', 'cafe', 'remote_work', 'WorkScore', 'A Nairobi staple. Reliable WiFi and great coffee before 10am. Not the most socket-friendly — arrive early to claim a wall seat. Best for focused solo work in the morning; gets packed at lunch.', 'linear-gradient(135deg, #4A2C1A 0%, #7A4A2A 100%)', '{"wifi_mbps":32,"noise_level":3,"sockets":"Scarce"}'::jsonb, ARRAY['☕ Great Coffee', '🌅 Early Bird Spot', '📍 Central']::text[], ARRAY['7am–10am ✓', '10am–12pm', '12pm–2pm ✗', '2pm–5pm']::text[], 7.4, 0, 'Min. KES 350', 'free'),
  ('Artcaffe — Village Market', 'Gigiri', 'cafe', 'remote_work', 'WorkScore', 'Large tables, reliable WiFi, and great food make it a solid all-day option. The indoor section is coolest and quietest.', 'linear-gradient(135deg, #3A2510 0%, #6A4520 100%)', '{"wifi_mbps":44,"noise_level":2,"sockets":"Moderate"}'::jsonb, ARRAY['🛒 Mall Location', '🍱 Great Food Menu', '🌡 Air-Conditioned']::text[], ARRAY['7am–10am ✓', '10am–12pm ✓', '12pm–2pm ✗', '2pm–5pm']::text[], 7.8, 0, 'Min. KES 450', 'free'),
  ('Roast by Carnivore', 'Langata', 'hotel', 'remote_work', 'WorkScore', 'One of Nairobi''s best-kept work secrets. The garden café attached to the Carnivore complex has fast WiFi, excellent power access, and almost no foot traffic on weekday mornings.', 'linear-gradient(135deg, #1A2E1A 0%, #2E502E 100%)', '{"wifi_mbps":70,"noise_level":1,"sockets":"Good"}'::jsonb, ARRAY['💎 Hidden Gem', '🌿 Garden Setting', '🤫 Quiet']::text[], ARRAY['7am–11am ✓', '11am–1pm ✓', '1pm–3pm', '3pm–5pm']::text[], 8.3, 0, 'Min. KES 700', 'free'),
  ('Pangani Social', 'Pangani', 'cafe', 'remote_work', 'WorkScore', 'An authentic neighbourhood café popular with local freelancers and creatives. Lower prices than the Westlands scene. WiFi is decent, sockets are scarce — bring a power bank.', 'linear-gradient(135deg, #3A1A10 0%, #6A3020 100%)', '{"wifi_mbps":38,"noise_level":2,"sockets":"Scarce"}'::jsonb, ARRAY['🏡 Local Feel', '💸 Budget-Friendly', '🎨 Creative Scene']::text[], ARRAY['8am–11am ✓', '11am–1pm', '3pm–6pm ✓']::text[], 7.6, 0, 'Min. KES 300', 'free'),
  ('Villa Rosa Kempinski — Lobby', 'Westlands', 'hotel', 'remote_work', 'WorkScore', 'When you need to look impressive. The Kempinski lobby café is ideal for client meetings. Fast WiFi, attentive service, great espresso.', 'linear-gradient(135deg, #1A1520 0%, #3A2A45 100%)', '{"wifi_mbps":88,"noise_level":1,"sockets":"Good"}'::jsonb, ARRAY['🏨 5-Star Setting', '🤝 Client Meetings', '⚡ Fast WiFi']::text[], ARRAY['8am–10am ✓', '10am–12pm ✓', '2pm–5pm ✓']::text[], 8.6, 0, 'Min. KES 1,200', 'free'),
  ('Kikwetu Café', 'Hurlingham', 'cafe', 'remote_work', 'WorkScore', 'A proudly Kenyan café with locally sourced beans. The Hurlingham branch is the most work-friendly — quieter, good WiFi, genuinely welcoming.', 'linear-gradient(135deg, #2A1A10 0%, #5A3520 100%)', '{"wifi_mbps":50,"noise_level":1,"sockets":"Moderate"}'::jsonb, ARRAY['🇰🇪 Proudly Kenyan', '☕ Local Beans', '🤫 Low Noise']::text[], ARRAY['7am–10am ✓', '10am–12pm ✓', '2pm–5pm ✓']::text[], 8, 0, 'Min. KES 380', 'free'),
  ('Space and Style Hub', 'Lavington', 'cowork', 'remote_work', 'WorkScore', 'A beautifully designed boutique coworking space in quiet Lavington. Max 30 desks. The vibe is calm and professional. One of the best value day passes in Nairobi.', 'linear-gradient(135deg, #151520 0%, #252535 100%)', '{"wifi_mbps":80,"noise_level":1,"sockets":"Excellent"}'::jsonb, ARRAY['🎨 Interior Design', '🤫 Silent Zones', '💎 Boutique']::text[], ARRAY['8am–12pm ✓', '2pm–6pm ✓']::text[], 8.2, 0, 'KES 1,000/day', 'paid');
